version: '3.1'
services:
  app:
    container_name: app
    image: app-springboot-postgresql
    build: .
    ports:
      - "8080:8080"
  alfa-battle-task1-websocket:
    image: arpmipg/alfa-battle:task1-websocket
    ports:
      - 8100:8100